const PDFDocument = require('pdfkit');

/**
 * Professional PDF Report Generator for SEO Audits
 */
class ReportService {
  /**
   * Build PDF stream and pipe to res
   */
  static generatePdf(auditData, stream) {
    const doc = new PDFDocument({
      size: 'A4',
      margin: 50,
      bufferPages: true
    });

    doc.pipe(stream);

    const primaryColor = '#4338CA'; // Indigo 700
    const darkColor = '#0F172A';    // Slate 900
    const grayColor = '#64748B';    // Slate 500
    const alertRed = '#DC2626';     // Red 600
    const alertAmber = '#D97706';   // Amber 600
    const greenColor = '#16A34A';   // Green 600

    const auditDate = auditData.createdAt
      ? new Date(auditData.createdAt).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })
      : new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });

    // ==========================================
    // PAGE 1: COVER PAGE
    // ==========================================
    doc.rect(0, 0, 595.28, 18).fill(primaryColor);

    doc.moveDown(4);
    doc.fillColor(primaryColor).fontSize(28).font('Helvetica-Bold').text('AI Website SEO Auditor', { align: 'center' });
    doc.moveDown(0.5);
    doc.fillColor(grayColor).fontSize(14).font('Helvetica').text('Comprehensive Technical, On-Page & AI Audit Report', { align: 'center' });

    doc.moveDown(4);
    // Score Badge Box
    const scoreBoxY = doc.y;
    doc.roundedRect(172, scoreBoxY, 250, 140, 12).fillAndStroke('#EEF2FF', '#C7D2FE');
    
    doc.fillColor(grayColor).fontSize(12).font('Helvetica-Bold').text('OVERALL SEO SCORE', 172, scoreBoxY + 25, { width: 250, align: 'center' });
    const scoreColor = (auditData.seoScore || 0) >= 80 ? greenColor : (auditData.seoScore || 0) >= 60 ? alertAmber : alertRed;
    doc.fillColor(scoreColor).fontSize(48).font('Helvetica-Bold').text(`${auditData.seoScore || 0}`, 172, scoreBoxY + 48, { width: 250, align: 'center' });
    doc.fillColor(grayColor).fontSize(12).font('Helvetica').text('out of 100 points', 172, scoreBoxY + 105, { width: 250, align: 'center' });

    doc.y = scoreBoxY + 180;
    doc.fillColor(darkColor).fontSize(12).font('Helvetica-Bold').text('Audit Details', { align: 'center' });
    doc.moveDown(0.5);
    doc.fillColor(grayColor).fontSize(11).font('Helvetica').text(`Target Website:  ${auditData.websiteUrl}`, { align: 'center' });
    doc.text(`Generated On:    ${auditDate}`, { align: 'center' });
    doc.text(`Pages Crawled:   ${auditData.pagesCrawled || 0} pages`, { align: 'center' });
    if (auditData.targetKeyword) {
      doc.text(`Target Keyword:  ${auditData.targetKeyword}`, { align: 'center' });
    }

    doc.moveDown(5);
    doc.fillColor(grayColor).fontSize(9).text('Confidential SEO Report • Generated by AI Website SEO Auditor', { align: 'center' });

    // ==========================================
    // PAGE 2: EXECUTIVE SUMMARY & CATEGORY SCORES
    // ==========================================
    doc.addPage();
    doc.rect(0, 0, 595.28, 8).fill(primaryColor);

    doc.fillColor(primaryColor).fontSize(18).font('Helvetica-Bold').text('1. Executive Summary & Category Scores');
    doc.moveDown(0.8);

    doc.fillColor(darkColor).fontSize(10).font('Helvetica').text(
      `This report documents the deep SEO health analysis conducted for ${auditData.websiteUrl}. Our engine validated technical crawlability, on-page tags, content depth, server responsiveness, structured data markup, and social signals.`,
      { lineGap: 3 }
    );
    doc.moveDown(1);

    // Category Score Table
    doc.fontSize(12).font('Helvetica-Bold').fillColor(darkColor).text('Category Breakdown (Weighted 100-Point Model):');
    doc.moveDown(0.5);

    const categories = [
      { name: 'Technical SEO', weight: '25%', score: auditData.technicalScore ?? auditData.seoScore },
      { name: 'On-Page SEO', weight: '25%', score: auditData.onPageScore ?? auditData.seoScore },
      { name: 'Content SEO', weight: '20%', score: auditData.contentScore ?? auditData.seoScore },
      { name: 'Performance', weight: '15%', score: auditData.performanceScore ?? 85 },
      { name: 'Structured Data', weight: '5%', score: auditData.structuredDataScore ?? 70 },
      { name: 'Social SEO', weight: '5%', score: auditData.socialScore ?? 80 },
      { name: 'Local SEO', weight: '5%', score: auditData.localScore ?? 75 }
    ];

    categories.forEach((cat, idx) => {
      const rowY = doc.y;
      doc.rect(50, rowY, 495, 24).fill(idx % 2 === 0 ? '#F8FAFC' : '#FFFFFF');
      doc.fillColor(darkColor).fontSize(10).font('Helvetica-Bold').text(cat.name, 60, rowY + 6);
      doc.fillColor(grayColor).font('Helvetica').text(`Weight: ${cat.weight}`, 260, rowY + 6);
      
      const sc = Number(cat.score) || 0;
      const cColor = sc >= 80 ? greenColor : sc >= 60 ? alertAmber : alertRed;
      doc.fillColor(cColor).font('Helvetica-Bold').text(`${sc} / 100`, 470, rowY + 6);
      doc.y = rowY + 28;
    });

    doc.moveDown(1.5);
    doc.fontSize(12).font('Helvetica-Bold').fillColor(darkColor).text('Issues Detected by Severity:');
    doc.moveDown(0.5);

    const issues = auditData.issues || [];
    const critCount = issues.filter(i => i.severity === 'critical').length;
    const highCount = issues.filter(i => i.severity === 'high').length;
    const medCount = issues.filter(i => i.severity === 'medium').length;
    const passCount = issues.filter(i => i.severity === 'passed').length;

    doc.fontSize(10).font('Helvetica').fillColor(alertRed).text(`• Critical Severity Blockers: ${critCount}`);
    doc.fillColor(alertAmber).text(`• High Priority Issues:       ${highCount}`);
    doc.fillColor('#4B5563').text(`• Medium Optimization Tasks:  ${medCount}`);
    doc.fillColor(greenColor).text(`• Passing SEO Checks:          ${passCount}`);

    // ==========================================
    // PAGE 3: TOP SEO ISSUES & RECOMMENDATIONS
    // ==========================================
    doc.addPage();
    doc.rect(0, 0, 595.28, 8).fill(primaryColor);

    doc.fillColor(primaryColor).fontSize(18).font('Helvetica-Bold').text('2. Priority Action Items & Fixes');
    doc.moveDown(0.8);

    const actionableIssues = issues.filter(i => i.severity === 'critical' || i.severity === 'high').slice(0, 5);

    if (actionableIssues.length === 0) {
      doc.fillColor(greenColor).fontSize(11).font('Helvetica').text('No Critical or High severity issues were detected! Your core on-page parameters comply with best practices.');
    } else {
      actionableIssues.forEach((issue, idx) => {
        const itemY = doc.y;
        if (itemY > 700) doc.addPage();

        const badgeColor = issue.severity === 'critical' ? alertRed : alertAmber;
        doc.fillColor(badgeColor).fontSize(10).font('Helvetica-Bold').text(`[${issue.severity.toUpperCase()}] ${issue.title}`);
        doc.moveDown(0.2);
        doc.fillColor(grayColor).fontSize(9).font('Helvetica').text(`URL: ${issue.page}`);
        doc.fillColor(darkColor).fontSize(9.5).text(`Problem: ${issue.description}`);
        doc.fillColor('#4338CA').fontSize(9.5).font('Helvetica-Bold').text(`Recommendation: ${issue.recommendation}`);
        doc.moveDown(1);
      });
    }

    // ==========================================
    // PAGE 4: STRATEGIC SEO ROADMAP (30-60-90 DAYS)
    // ==========================================
    doc.addPage();
    doc.rect(0, 0, 595.28, 8).fill(primaryColor);
    doc.fillColor(primaryColor).fontSize(18).font('Helvetica-Bold').text('3. Strategic SEO Growth Roadmap (4 Phases)');
    doc.moveDown(0.8);

    doc.fillColor(darkColor).fontSize(9.5).font('Helvetica').text(
      'A structured 30-60-90 day execution plan prioritized by technical severity and organic ranking impact:',
      { lineGap: 3 }
    );
    doc.moveDown(0.8);

    const roadmapPhases = [
      {
        num: 'Phase 1 (Days 1–14)',
        title: 'Foundation & Crawlability Triage',
        desc: 'Enforce HTTPS, fix 404 dead-ends, remove erroneous noindex tags, and inject mobile viewport.'
      },
      {
        num: 'Phase 2 (Days 15–30)',
        title: 'On-Page Relevance & Metadata Optimization',
        desc: 'Optimize title tags, meta descriptions, image alt tags, canonicals, and expand thin content.'
      },
      {
        num: 'Phase 3 (Days 31–60)',
        title: 'Backlinks & Anchor Words Architecture',
        desc: 'Restructure internal links, eliminate empty anchors, diversify anchor text, and pitch link outreach.'
      },
      {
        num: 'Phase 4 (Days 61–90+)',
        title: 'Authority Scaling, Rich Snippets & Core Web Vitals',
        desc: 'Deploy Schema.org JSON-LD (LocalBusiness, FAQ), optimize TTFB / LCP, and expand topic clusters.'
      }
    ];

    roadmapPhases.forEach((p, idx) => {
      const pY = doc.y;
      if (pY > 700) doc.addPage();
      doc.rect(50, pY, 495, 48).fill(idx % 2 === 0 ? '#EEF2FF' : '#F8FAFC');
      doc.fillColor(primaryColor).fontSize(10).font('Helvetica-Bold').text(p.num, 60, pY + 8);
      doc.fillColor(darkColor).fontSize(9.5).font('Helvetica-Bold').text(p.title, 175, pY + 8);
      doc.fillColor(grayColor).fontSize(8.5).font('Helvetica').text(p.desc, 60, pY + 24, { width: 470 });
      doc.y = pY + 54;
    });

    // ==========================================
    // PAGE 5: BACKLINK & ANCHOR WORDS PROFILE
    // ==========================================
    doc.addPage();
    doc.rect(0, 0, 595.28, 8).fill(primaryColor);
    doc.fillColor(primaryColor).fontSize(18).font('Helvetica-Bold').text('4. Backlink & Anchor Words Profile');
    doc.moveDown(0.8);

    doc.fillColor(darkColor).fontSize(9.5).font('Helvetica').text(
      'Analysis of internal and outbound anchor text distribution, backlink health, and recommended anchor text targets:',
      { lineGap: 3 }
    );
    doc.moveDown(0.8);

    const anchorAdvice = [
      { type: 'Branded Anchors (Target: 45-55%)', status: 'Healthy', note: 'Use brand name in primary hyperlinks to establish authoritative entity trust.' },
      { type: 'Exact Keyword Match (Target: 10-15%)', status: 'Monitored', note: 'Limit exact match keywords to avoid Google Penguin over-optimization flags.' },
      { type: 'Partial / LSI Match (Target: 20-25%)', status: 'Recommended', note: 'Use natural conversational phrases including target topics and locations.' },
      { type: 'Generic / Empty Anchors (Target: < 5%)', status: 'Action Required', note: 'Replace "click here" and empty <a> links with contextual topic labels.' }
    ];

    anchorAdvice.forEach((item, idx) => {
      const aY = doc.y;
      if (aY > 700) doc.addPage();
      doc.rect(50, aY, 495, 42).fill(idx % 2 === 0 ? '#F8FAFC' : '#FFFFFF');
      doc.fillColor(darkColor).fontSize(9.5).font('Helvetica-Bold').text(item.type, 60, aY + 8);
      doc.fillColor(primaryColor).fontSize(8.5).font('Helvetica-Bold').text(item.status, 450, aY + 8);
      doc.fillColor(grayColor).fontSize(8.5).font('Helvetica').text(item.note, 60, aY + 22, { width: 470 });
      doc.y = aY + 48;
    });

    // ==========================================
    // PAGE 6: CRAWLED PAGES SUMMARY
    // ==========================================
    const pages = auditData.pages || [];
    if (pages.length > 0) {
      doc.addPage();
      doc.rect(0, 0, 595.28, 8).fill(primaryColor);
      doc.fillColor(primaryColor).fontSize(18).font('Helvetica-Bold').text('5. Crawled Pages Inventory');
      doc.moveDown(0.8);

      pages.slice(0, 10).forEach((p, idx) => {
        const pY = doc.y;
        if (pY > 720) doc.addPage();
        
        doc.rect(50, pY, 495, 36).fill(idx % 2 === 0 ? '#F8FAFC' : '#FFFFFF');
        doc.fillColor(darkColor).fontSize(9).font('Helvetica-Bold').text((p.url || '').substring(0, 75), 58, pY + 5);
        doc.fillColor(grayColor).fontSize(8.5).font('Helvetica').text(
          `Status: ${p.statusCode || 200} | Words: ${p.wordCount || 0} | Images: ${p.imageCount || 0} | Links: ${p.internalLinkCount || 0} Int / ${p.externalLinkCount || 0} Ext`,
          58, pY + 20
        );
        doc.fillColor(primaryColor).fontSize(9).font('Helvetica-Bold').text(`Score: ${p.seoScore || 'N/A'}`, 480, pY + 12);
        doc.y = pY + 40;
      });
    }

    doc.end();
  }
}

module.exports = ReportService;
